version: "3.9"
services:
  react-calculator-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: react-calculator-prod
    restart: always
    ports:
      - 3000:3000
    networks:
      - network
networks:
  network: