version: "3.9"
services:
 react-calculator:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: react-calculator
   restart: always
   ports:
     - 3000:3000
   volumes:
     - .:/app
     - /app/node_modules
   networks:
     - network
networks:
 network: